#!/usr/bin/env node
/* ============================================================
   Inlines balldetector.js into the two companion HTML pages.

       node build_webui.mjs           write the pages
       node build_webui.mjs --check   verify only, exit 1 if out of date

   The pages must stay self-contained single files: they are opened
   straight from the filesystem on a phone, where a relative
   <script src> does not load reliably. So the engine is duplicated
   into them on purpose — but generated, never hand-maintained.

   Edit the engine in balldetector.js. Everything between the markers
   in the HTML files is overwritten without warning.
   ============================================================ */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = 'balldetector.js';
const TARGETS = ['everflo_control_panel.html', 'everflo_image_diagnostics.html'];
/* The sketch serves the same engine at /motor.js so the device page can show
   a reading without anyone transferring a file to a phone. It is a separate
   header, not part of the page string, because the page is copied into a
   String on every request and ~90 kB of engine would not fit in heap. */
const HEADER = 'balldetector_js.h';

const BEGIN = '/* === ENGINE:BEGIN — generated from balldetector.js, do not edit here === */';
const END = '/* === ENGINE:END === */';

const check = process.argv.includes('--check');
const engine = readFileSync(join(here, SOURCE), 'utf8').replace(/\n+$/, '\n');

let stale = 0;
for (const name of TARGETS) {
  const path = join(here, name);
  const html = readFileSync(path, 'utf8');

  const from = html.indexOf(BEGIN);
  const to = html.indexOf(END);
  if (from === -1 || to === -1 || to < from) {
    console.error(`${name}: markers missing or reversed — refusing to touch the file.`);
    process.exit(2);
  }

  const wanted = html.slice(0, from + BEGIN.length) + '\n' + engine + html.slice(to);
  if (wanted === html) {
    console.log(`${name}: up to date`);
    continue;
  }
  stale++;
  if (check) {
    console.error(`${name}: OUT OF DATE — run: node build_webui.mjs`);
    continue;
  }
  writeFileSync(path, wanted);
  console.log(`${name}: updated`);
}

/* The C++ header. A raw string literal, so the delimiter must not appear in
   the engine — )JS" does not occur in JavaScript, but check anyway rather
   than emit a file that fails to compile in a confusing way. */
if (engine.includes(')JS"')) {
  console.error(`${SOURCE}: contains the raw-string delimiter )JS" — pick another delimiter.`);
  process.exit(2);
}
/* FNV-1a over the engine source. A content hash rather than a constant someone
   has to remember to bump, because it cannot drift from the code. It is the
   admin page's cache key, and since v1.9.7 the device reports it with every
   upload so a stored reading can be attributed to the engine that was live at
   the time. Computed here because both the header and the admin module need
   it. */
let h = 2166136261;
for (let i = 0; i < engine.length; i++) {
  h ^= engine.charCodeAt(i); h = Math.imul(h, 16777619);
}
const engineVersion = (h >>> 0).toString(16);

const header = `/* GENERATED by build_webui.mjs from ${SOURCE} — do not edit.
   Served at /motor.js so the device page can compute a reading itself. */
#pragma once
#define ENGINE_VERSION "${engineVersion}"
static const char BALLDETECTOR_JS[] = R"JS(
${engine})JS";
`;
const headerPath = join(here, HEADER);
let headerNow = '';
try { headerNow = readFileSync(headerPath, 'utf8'); } catch { /* first run */ }
if (headerNow !== header) {
  stale++;
  if (check) console.error(`${HEADER}: OUT OF DATE — run: node build_webui.mjs`);
  else { writeFileSync(headerPath, header); console.log(`${HEADER}: updated`); }
} else {
  console.log(`${HEADER}: up to date`);
}

/* The admin Worker serves the same engine so uploaded frames can be analysed
   in the browser, where the calibration actually applies. JSON.stringify does
   the escaping, so no delimiter in the engine can break the module. */
const ADMIN = join(here, 'cloud', 'admin', 'src', 'engine.js');
const adminMod = `/* GENERATED by build_webui.mjs from ${SOURCE} — do not edit. */\n` +
  `export const ENGINE = ${JSON.stringify(engine)};\n` +
  `export const ENGINE_VERSION = ${JSON.stringify(engineVersion)};\n`;
let adminNow = '';
try { adminNow = readFileSync(ADMIN, 'utf8'); } catch { /* first run */ }
if (adminNow !== adminMod) {
  stale++;
  if (check) console.error(`cloud/admin/src/engine.js: OUT OF DATE — run: node build_webui.mjs`);
  else { writeFileSync(ADMIN, adminMod); console.log('cloud/admin/src/engine.js: updated'); }
} else {
  console.log('cloud/admin/src/engine.js: up to date');
}

if (check && stale) process.exit(1);

// Belt and braces: the engine must be byte-identical in both pages.
if (!check) {
  const cut = (s) => s.slice(s.indexOf(BEGIN), s.indexOf(END) + END.length);
  const [a, b] = TARGETS.map((n) => cut(readFileSync(join(here, n), 'utf8')));
  if (a !== b) {
    console.error('MISMATCH: the inlined engines differ between the two pages.');
    process.exit(3);
  }
  console.log('engine byte-identical in both pages');
}

/* The HMAC-SHA256 that signs control requests (v1.12.0) lives twice — in her
   page inside the sketch and in the control panel — because her page must
   work without /motor.js. Two hand-kept copies are exactly what broke a
   quality gate in 2026-08, so both runs check they are identical; if they
   are not, every press from one of them is refused. The copies are checked
   against node:crypto by tools/test_hmac.mjs. */
{
  const block = (name) => {
    const t = readFileSync(join(here, name), 'utf8');
    const a = t.indexOf('const SHA_K=['), b = t.indexOf('\nfunction hmacHex(', a), e = t.indexOf('\n}\n', b);
    return a < 0 || b < 0 || e < 0 ? null : t.slice(a, e + 2);
  };
  const [pg, cp] = ['everflo_remote_control.ino', 'everflo_control_panel.html'].map(block);
  if (!pg || !cp || pg !== cp) {
    console.error('MISMATCH: the HMAC block differs between her page (the .ino) and the control panel.');
    process.exit(4);
  }
  console.log('control-key HMAC identical in her page and the control panel');
}
